### PR TITLE
update electron-prebuilt to 0.36.3

### PR DESCRIPTION
**Pull request by JamesKyburz**

### CODE REVIEW

**Comment by mattdesl** [comment]
thanks! :+1:

**Comment by JamesKyburz** [comment]
@mattdesl That was quick thx!

**Comment by mattdesl** [comment]
Ah, it seems like this might have some problems since the Electron API has changed. I will go about fixing..

**Comment by JamesKyburz** [comment]
I got some warnings but did test it worked.

```
(electron) loadUrl is deprecated. Use loadURL instead.
2016-01-08 16:09:43.511 Electron Helper[28764:2905905] Couldn't set selectedTextBackgroundColor from default ()
```

**Comment by mattdesl** [comment]
can you try latest npm version (2.6.0) and let me know? I fixed the loadURL warning.

**Comment by JamesKyburz** [comment]
Tested with

node 4.2.4/5.4.0 & npm 2.14.12/2.6.0/3.3.12

The warning about `Electron Helper[32504:2932220] Couldn't set selectedTextBackgroundColor from default ()` was displayed by all

However when testing the canvas example with `--exec` nothing happens, without `--exec` it worked.

Testing that now.

**Comment by mattdesl** [comment]
Ok, there are a few breaking changes in latest electron (I wish they would use semver..).

I am going to revert this, push a patch, and then push this back as a new major version of hihat.

**Comment by JamesKyburz** [comment]
Agreed I wish semver was used!

Ok
Sorry should have dug deeper into the electron changelog. All I wanted was more es2015 love :)

**Comment by mattdesl** [comment]
Actually it looks like it was just my mistake, everything seems to be working fine! I am going to push a patch to the `electron-canvas-to-buffer` module to remove a warning.

**Comment by mattdesl** [comment]
Can you pull from master, npm install, and then run:

```
npm run example
```

It should add a `canvas.png` in the hihat directory, if all goes well. Seems to be working fine on my machine now. :tada:

**Comment by JamesKyburz** [comment]
:zap:*It worked all along!*:zap:

Typed ```hihat --node --exec ./pic.js >``` instead of ```hihat ./pic.js --node --exec  >```

Thanks for your help and awesome work!

**Comment by mattdesl** [comment]
Ah cool, sounds like a bug with arg parsing. I will open another issue. :smile:

**Pull request merged**
