### PR TITLE
Filename expansion for less fortunate shells

### PR DESCRIPTION
**Pull request by vweevers**
Please help that poor Windows command line prompt. We need more hihat.

### CODE REVIEW

**Comment by mattdesl** [comment]
Cool, thanks! The only nitpicks I have with this:

- It assumes the entries are at the start of the command; so it breaks existing `hihat --node test/*.js` scripts
- it uses promises, whereas the rest of hihat is based on callbacks. Some care might need to be taken to avoid having errors implicitly caught by whatever promise implementation Sindre is using

I am going to look into fixing this though.

**Comment by mattdesl** [comment]
See here: https://github.com/Jam3/hihat/tree/feature/windows-glob

Because globby uses promises, now any error in hihat will be implicitly caught by the underlying promise implementation. :cry: Kinda annoying; I might search around for a non-promise module.

**Comment by vweevers** [comment]
Yeah, promises were not my choice, globby used to be callback based and I didn't know of a better module.

**Comment by vweevers** [comment]
I can take some time (end of week) to write a simple concatenating wrapper around [glob-stream](https://github.com/wearefractal/glob-stream). That seems to be the best option until multiple pattern support is [implemented in glob-fs](https://github.com/jonschlinkert/glob-fs#todo).

**Comment by mattdesl** [comment]
I think it's OK to use `globby` for now, especially since Hihat is mainly a CLI app, so the implicit catch isn't as big a deal.

If my `feature/windows-glob` branch is working for you, I can merge it in. I don't have windows to test. :smile:

**Comment by vweevers** [comment]
Just tried `feature/windows-glob`: `hihat --node test/*.js` and `hihat test/*.js --node` both work :+1:

**Comment by vweevers** [comment]
As well as multiple patterns, so all good.

**Comment by mattdesl** [comment]
Sorry for the suuuuuper long delay on this. Merged in 2.6.0.

**Comment by vweevers** [comment]
Thanks! :ok_hand:

**Pull request merged**
